name: safest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.0

  # Routing
  go_router: ^14.3.0

  # UI & Styling
  gradient_borders: ^1.0.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Sound
  audioplayers: ^5.2.1
  share_plus: ^12.0.1
  just_audio: ^0.10.5
  flutter_local_notifications: ^19.5.0

  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/sounds/

  # Fonts
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
